### ISSUE TITLE
Unintended Inclusion of macOS Release Package in Linux Release

### ISSUE THREAD

**Issue by mooncanel** [lemorage/sublime-clannad-theme#1]
The color scheme is pretty nice. But I noticed a bug when downloading the linux release pkg, which contains a macOS release pkg within it. I think this should be an unexpected inclusion, and this could be something wrong with the gh actions.

**Comment by lemorage** [comment]
Indeed. I see the issue.

**Comment by lemorage** [comment]
Resolved as [4939a6](https://github.com/lemorage/sublime-clannad-theme/commit/4939a6fdd63965c7b0c0be371e81f5315bfbaf6e)
